### PR TITLE
Update bower support

### PR DESCRIPTION
**Pull request by 0x-r4bbit**

### CODE REVIEW

**Comment by wmluke** [comment]
Hi Pascal,  

Thanks for the pull-request!  

I'm super busy through this weekend, but I'll take a look at this early next week.

Thanks again,
Luke

**Comment by 0x-r4bbit** [comment]
Allright then! :)

**Comment by 0x-r4bbit** [comment]
Progress?

**Comment by 0x-r4bbit** [comment]
Thank you @wmluke !

**Comment by wmluke** [comment]
No, thank you for the pull request!

**Pull request merged**
